apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.16.1.229
    path: "/opt/mysql"

