kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: paas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      # Comment the following annotation if Dashboard must not be deployed on master
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: |
          [
            {
              "key": "dedicated",
              "operator": "Equal",
              "value": "master",
              "effect": "NoSchedule"
            }
          ]
    spec:
      containers:
      - name: mysql
        image: registry.cn-hangzhou.aliyuncs.com/jc-network-web2/mysqlwithtable:8.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql_root_password
        - name: MYSQL_DATABASE
          value: mysql_dbname
        - name: MYSQL_USER
          value: mysql_username
        - name: MYSQL_PASSWORD
          value: mysql_password
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
