apiVersion: v1
kind: Service
metadata:
  name: svc-redis-cluster
  namespace: platform
  labels:
    name: svc-redis-cluster
spec:
  #type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    #nodePort: 31079
  clusterIP: None
  selector:
    name: sts-redis-cluster
