apiVersion: v1
kind: Service
metadata:
  name: svc-redis-cluster-np
  namespace: platform
  labels:
    name: svc-redis-cluster-np
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 31009
  type: NodePort
  externalIPs:
  - 116.62.67.216
  - 116.62.62.20
  selector:
    name: sts-redis-cluster
