apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sts-redis-cluster
  namespace: platform
spec:
  serviceName: "svc-redis-cluster"
  replicas: 6
  template:
    metadata:
      labels:
        name: sts-redis-cluster
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cntr-redis-cluster
        image: registry.cn-hangzhou.aliyuncs.com/jc-network-web2/redis-in-k8s:4.0.8
        imagePullPolicy: IfNotPresent
        env:
        - name: CLUSTER
          value: "true"
        - name: REDIS_PORT
          value: "6379"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #- name: PASSWORD
        #  value: jc123456
        ports:
        - containerPort: 6379
      imagePullSecrets:
      - name: registry-secret
 
#       volumeMounts:
#        - name: rediscluster
#          mountPath: /data/redis
#        securityContext:
#          capabilities: {}
#          privileged: true
#  volumeClaimTemplates:
#  - metadata:
#      name: rediscluster
#      annotations:
#        volume.beta.kubernetes.io/storage-class: "fast"
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      resources:
#        requests:
#          storage: 1Gi
